### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by danielbreves**
:v:

/cc @zendesk/vegemite

### CODE REVIEW

**Comment by svizzari** [comment]
> Improve styling and add support for all locations

screenshot?

**Comment by adammw** [comment]
:+1:

**Comment by danielbreves** [comment]
screen shot 2016-06-29 at 12 03 43 pm

**Comment by danielbreves** [comment]
screen shot 2016-06-29 at 12 05 37 pm

**Comment by danielbreves** [comment]
screen shot 2016-06-29 at 12 05 59 pm

**Comment by danielbreves** [comment]
To do: https://zendesk.atlassian.net/browse/AF-373

**Comment by svizzari** [comment]
👍

**Pull request merged**
