### PR TITLE
Fix promise check for IE

### PR DESCRIPTION
**Pull request by danielbreves**
:v:

/cc @zendesk/vegemite

### CODE REVIEW

**Comment by sandlerr** [comment]
what version of IE? Can you make a comment?

**Comment by sandlerr** [comment]
We could use a promise polyfill

**Comment by svizzari** [comment]
Haha, https://github.com/zendesk/sdk_repl_app/commit/2fab6c3803fe7d0bd339605b249df443b20e7cbf

**Comment by danielbreves** [comment]
@sandlerr we already do, this promise comes from ZAF SDK. Also, `Promise` is not available on any versions of IE. See https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility.

**Comment by danielbreves** [comment]
@svizzari what happened to that helper?

**Comment by danielbreves** [comment]
@svizzari 👍?

**Comment by svizzari** [comment]
@danielbreves 

> ...where did that helper go?

I refactored it out, thinking that an `instanceof` check would be sufficient 😿

**Comment by svizzari** [comment]
👍

**Comment by ocke** [comment]
I would prefer to ditch all these $.promise and RSVP promises in favour of 1 Promise polyfill in all of lotus. But anyway, this is a easy fix 👍

**Comment by sandlerr** [comment]
is `value` always going to be an object? Otherwise this will throw

**Comment by danielbreves** [comment]
@sandlerr all [primitives](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) are wrapped by objects in JavaScript, except for `null` or `undefined`, in which case this will throw. Good catch!

**Comment by danielbreves** [comment]
💇  https://github.com/zendesk/sdk_repl_app/pull/8

**Pull request merged**
